import numpy as np

x1, y1 = np.genfromtxt('plaettchendaten.txt' ,unpack=True)
x2, y2 = np.genfromtxt('plaettchendaten2.txt' ,unpack=True)
x3, y3 = np.genfromtxt('plaettchendaten3.txt' ,unpack=True)
x4, y4 = np.genfromtxt('plaettchendaten4.txt' ,unpack=True)
x5, y5 = np.genfromtxt('plaettchendaten5.txt' ,unpack=True)
x6, y6 = np.genfromtxt('plaettchendaten6.txt' ,unpack=True)
x7, y7 = np.genfromtxt('plaettchendaten7.txt' ,unpack=True)
x8, y8 = np.genfromtxt('plaettchendaten8.txt' ,unpack=True)
xrad1 = np.abs((((2*np.pi)/360)*x1))
xrad2 = (((2*np.pi)/360)*x2)
xrad3 = (((2*np.pi)/360)*x3)
xrad4 = (((2*np.pi)/360)*x4)
xrad6 = (((2*np.pi)/360)*x6)
xrad5 = (((2*np.pi)/360)*x5)
xrad7 = (((2*np.pi)/360)*x7)
xrad8 = (((2*np.pi)/360)*x8)
lambdavac = 632.99*10**-9
T = 1*10**(-3)
n1 = (T*xrad1**2)/(T*xrad1**2-y1*lambdavac)
print('Messung 1: ')
print(np.mean(n1))
print(np.std(n1))
n2 = (T*xrad2**2)/(T*xrad2**2-y2*lambdavac)
print('Messung 2: ')
print(np.mean(n2))
print(np.std(n2))
n3 = (T*xrad3**2)/(T*xrad3**2-y3*lambdavac)
print('Messung 3: ')
print(np.mean(n3))
print(np.std(n3))
n4 = (T*xrad4**2)/(T*xrad4**2-y4*lambdavac)
print('Messung 4: ')
print(np.mean(n4))
print(np.std(n4))
n5 = (T*xrad5**2)/(T*xrad5**2-y5*lambdavac)
print('Messung 5: ')
print(np.mean(n5))
print(np.std(n5))
n6 = (T*xrad6**2)/(T*xrad6**2-y6*lambdavac)
print('Messung 6: ')
print(np.mean(n6))
print(np.std(n6))
n7 = (T*xrad7**2)/(T*xrad7**2-y7*lambdavac)
print('Messung 7: ')
print(np.mean(n7))
print(np.std(n7))
n8 = (T*xrad8**2)/(T*xrad8**2-y8*lambdavac)
print('Messung 8: ')
print(np.mean(n8))
print(np.std(n8))
data = [np.mean(n1), np.mean(n2), np.mean(n3), np.mean(n4), np.mean(n5), np.mean(n6), np.mean(n7), np.mean(n8)]
print('Mittelwert = ')
print(np.mean(data))
print(np.std(data))
