import numpy as np


def n(x, T, l, M,d):
    return 1/(1-(l*M)/(2*T*d*x))

x1, y1 = np.genfromtxt('plaettchendaten.txt' ,unpack=True)
x2, y2 = np.genfromtxt('plaettchendaten2.txt' ,unpack=True)
x3, y3 = np.genfromtxt('plaettchendaten3.txt' ,unpack=True)
x4, y4 = np.genfromtxt('plaettchendaten4.txt' ,unpack=True)
x5, y5 = np.genfromtxt('plaettchendaten5.txt' ,unpack=True)
x6, y6 = np.genfromtxt('plaettchendaten6.txt' ,unpack=True)
x7, y7 = np.genfromtxt('plaettchendaten7.txt' ,unpack=True)
x8, y8 = np.genfromtxt('plaettchendaten8.txt' ,unpack=True)
xrad1 = np.abs((((2*np.pi)/360)*x1))
xrad2 = (((2*np.pi)/360)*x2)
xrad3 = (((2*np.pi)/360)*x3)
xrad4 = (((2*np.pi)/360)*x4)
xrad6 = (((2*np.pi)/360)*x6)
xrad5 = (((2*np.pi)/360)*x5)
xrad7 = (((2*np.pi)/360)*x7)
xrad8 = (((2*np.pi)/360)*x8)
lambdavac = 632.99*10**-9
T = 1*10**(-3)
d =(((2*np.pi)/360)*10)
n1 =n(xrad1,T,lambdavac,y1,d)
print('Messung 1: ')
print(np.mean(n1))
print(np.std(n1))
n2 =n(xrad2,T,lambdavac,y2,d)
print('Messung 2: ')
print(np.mean(n2))
print(np.std(n2))
n3 =n(xrad3,T,lambdavac,y3,d)
print('Messung 3: ')
print(np.mean(n3))
print(np.std(n3))
n4 =n(xrad4,T,lambdavac,y4,d)
print('Messung 4: ')
print(np.mean(n4))
print(np.std(n4))
n5 =n(xrad5,T,lambdavac,y5,d)
print('Messung 5: ')
print(np.mean(n5))
print(np.std(n5))
n6 =n(xrad6,T,lambdavac,y6,d)
print('Messung 6: ')
print(np.mean(n6))
print(np.std(n6))
n7 =n(xrad7,T,lambdavac,y7,d)
print('Messung 7: ')
print(np.mean(n7))
print(np.std(n7))
n8 =n(xrad8,T,lambdavac,y8,d)
print('Messung 8: ')
print(np.mean(n8))
print(np.std(n8))
data = [np.mean(n1), np.mean(n2), np.mean(n3), np.mean(n4), np.mean(n5), np.mean(n6), np.mean(n7), np.mean(n8)]
print('Mittelwert = ')
print(np.mean(data))
print(np.std(data))
